import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# =========================
# LOAD DATA
# =========================
FILE = "od_with_travel_time_res7.csv"

od = pd.read_csv(FILE)

# =========================
# BASIC COUNTS
# =========================
num_od_pairs = len(od)
num_zones = len(set(od["o_hex"]).union(set(od["d_hex"])))
total_trips = od["trips"].sum()

print("===================================")
print("ROCKINGHAM RES 7 DEMAND STATISTICS")
print("===================================")
print(f"Total OD pairs: {num_od_pairs}")
print(f"Total unique zones: {num_zones}")
print(f"Total trips: {total_trips}")
print()

# =========================
# TRIPS PRODUCED & ATTRACTED
# =========================
produced = od.groupby("o_hex")["trips"].sum().rename("produced")
attracted = od.groupby("d_hex")["trips"].sum().rename("attracted")

zone_stats = pd.concat([produced, attracted], axis=1).fillna(0)
zone_stats["total"] = zone_stats["produced"] + zone_stats["attracted"]

print("Top 10 zones by total demand:")
print(zone_stats.sort_values("total", ascending=False).head(10))
print()

# =========================
# HIGH DEMAND ZONES
# =========================
mean_demand = zone_stats["total"].mean()
high_demand_zones = zone_stats[zone_stats["total"] > mean_demand]

print(f"Mean zone demand: {mean_demand:.2f}")
print(f"Zones above mean demand: {len(high_demand_zones)}")
print()

# =========================
# DEMAND DISTRIBUTION PLOTS
# =========================

plt.figure(figsize=(8,5))
sns.histplot(zone_stats["total"], bins=20, kde=True)
plt.title("Distribution of Total Demand per Zone")
plt.xlabel("Trips per Zone")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(od["trips"], bins=20, kde=True)
plt.title("Distribution of Trips per OD Pair")
plt.xlabel("Trips per OD Pair")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()

# =========================
# TRAVEL TIME STATISTICS
# =========================
print("Travel Time Statistics (minutes):")
print(od["travel_time"].describe())
print()

# =========================
# DEMAND CONCENTRATION
# =========================
top_10_percent_threshold = zone_stats["total"].quantile(0.90)
top_zones = zone_stats[zone_stats["total"] >= top_10_percent_threshold]

print(f"Top 10% demand threshold: {top_10_percent_threshold:.2f}")
print(f"Number of zones in top 10%: {len(top_zones)}")

share_top_zones = top_zones["total"].sum() / total_trips
print(f"Share of total demand generated by top 10% zones: {share_top_zones:.2%}")